name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"  # Chạy mỗi ngày lúc 00:00 UTC
  workflow_dispatch:      # Cho phép chạy thủ công
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Generate snake game
      uses: Platane/snk@v3
      with:
        github_user_name: DucEvil
        outputs: |
          output/github-contribution-grid-snake.svg
          output/github-contribution-grid-snake-dark.svg?palette=github-dark
      
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add output/
        git commit -m "Update snake animation" || exit 0
        git push
